### ISSUE TITLE
'make arty_minisoc' returns error

### ISSUE THREAD

**Issue by GuzTech** [enjoy-digital/arty-soc#1]
I've followed steps 1 to 5 without any problems, but when I run `make arty_minisoc` I get the following error trace:

```
rm -rf build
./arty_base.py --with-ethernet --nocompile-gateware --cpu-type lm32
Traceback (most recent call last):
  File "./arty_base.py", line 272, in <module>
    main()
  File "./arty_base.py", line 265, in main
    soc = cls(platform, **soc_sdram_argdict(args))
  File "./arty_base.py", line 229, in __init__
    BaseSoC.__init__(self, *args, **kwargs)
  File "./arty_base.py", line 139, in __init__
    **kwargs)
  File "/home/guztech/Software/litex/litex/litex/soc/integration/soc_sdram.py", line 39, in __init__
    SoCCore.__init__(self, platform, clk_freq, **kwargs)
  File "/home/guztech/Software/litex/litex/litex/soc/integration/soc_core.py", line 119, in __init__
    self.submodules.timer0 = timer.Timer()
  File "/home/guztech/Software/litex/litex/litex/soc/cores/timer.py", line 9, in __init__
    self._load = CSRStorage(width)
  File "/home/guztech/Software/litex/litex/litex/soc/interconnect/csr.py", line 225, in __init__
    _CompoundCSR.__init__(self, size, name)
  File "/home/guztech/Software/litex/litex/litex/soc/interconnect/csr.py", line 107, in __init__
    _CSRBase.__init__(self, size, name)
  File "/home/guztech/Software/litex/litex/litex/soc/interconnect/csr.py", line 37, in __init__
    raise ValueError("Cannot extract CSR name from code, need to specify.")
ValueError: Cannot extract CSR name from code, need to specify.
make: *** [Makefile:11: arty_minisoc] Error 1
```

Thinking it might be related to https://github.com/m-labs/migen/issues/62 I changed the shebang of arty_base.py to be `python3.5` because I have normally have Python 3.6, and then I get the following error:

```
rm -rf build
./arty_base.py --with-ethernet --nocompile-gateware --cpu-type lm32
Traceback (most recent call last):
  File "./arty_base.py", line 5, in <module>
    from litex.gen import *
ImportError: No module named 'litex'
```

Probably because I installed litex with Python 3.6 instead of 3.5. Do you know what is causing this problem?

**Comment by mithro** [comment]
@GuzTech You are correct and the issue you are having is a Python 3.5 verse Python 3.6 compatibility problem. You will need to rerun the `python setup.py` commands with `python3.5 setup.py` instead.

If you are on Ubuntu you might want to try my  setup script at https://gist.github.com/mithro/604da515edc1061a77a8ee6c1fe729e6 to get a working environment.

**Comment by GuzTech** [comment]
@mithro Thanks Tim. I'm running Arch Linux, but I'll try your (modified) setup script.

**Comment by GuzTech** [comment]
I made an alias for python to point to python3.5, but that didn't work. However, like I pointed out earlier, if you simply change the shebang to python3.5 then it works.
